// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs", "newtab_stories_1, newtab_stories_2, newtab_stories_3, newtab_stories_4, newtab_stories_5, newtab_stories_6, newtab_billboard");
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.activity-stream.topSitesRows", 2);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.blocked", "{\"Ah7lSVYCzNULDsq5mnZyfw==\":1}");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://duckduckgo.com/\",\"baseDomain\":\"duckduckgo.com\",\"label\":\"DuckDuckGo\"},{\"url\":\"https://duck.com/\",\"label\":\"Duck.com\"},{\"url\":\"https://duck.ai/\",\"label\":\"Duck.ai\"},null,null,null,{\"url\":\"https://example.com/\",\"label\":\"Example Domain\"}]");
