// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "bfc8f0be-c4a3-4ad9-8c82-744c1eb6049f");
user_pref("app.update.background.previous.reasons", "[\"unsupported OS\"]");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1752839840);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1752839839);
user_pref("app.update.lastUpdateTime.suggest-ingest", 1752839839);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{c870492c-09c4-4f73-bdb4-35dddf386166}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1752839838);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 155);
user_pref("browser.ml.chat.nimbus", "simplified-chatbot-onboarding-short-copy-1-step-rollout:treatment-c-short-copy-1-step");
user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs", "newtab_stories_1, newtab_stories_2, newtab_stories_3, newtab_stories_4, newtab_stories_5, newtab_stories_6");
user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs.counts", "1,1,1,1,1,1");
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc-positions", "2,4,8,13,17,20");
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", "{\"CAISF3NvbG8gYWkgd2Vic2l0ZSBjcmVhdG9y\":[1752839843058]}");
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a9760f4b-f07f-4384-ae5f-308ab16f91cc}");
user_pref("browser.newtabpage.activity-stream.system.showSponsoredCheckboxes", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.preonboarding.enrolledInOnTrainRollout", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1752839839);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1752839839940");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1752861439940");
user_pref("browser.search.region", "GB");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20250707120347");
user_pref("browser.startup.homepage_override.mstone", "140.0.4");
user_pref("browser.startup.lastColdStartupCheck", 1752839839);
user_pref("browser.tabs.groups.smart.enabled", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1752839839);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"sidebar-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":22,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("captchadetection.lastSubmission", 1752839);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "3f575df2-72a1-4527-8066-5f975c64c995");
user_pref("datareporting.dau.cachedUsageProfileID", "4785d28d-388b-4b05-993a-d58ef4a2466f");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1752839841576");
user_pref("distribution.iniFile.exists.appversion", "140.0.4");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "GB");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "17fc1c99e5f04b29a10b849efeefe404");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECDBuHx5yG8sVBAiPerugJGhARg==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250707120347");
user_pref("extensions.lastAppVersion", "140.0.4");
user_pref("extensions.lastPlatformVersion", "140.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"af5a13d4-9045-48f0-9f0d-63bb7278493e\",\"newtab@mozilla.org\":\"37db5796-7702-43f3-8804-e05d59ff6217\",\"pictureinpicture@mozilla.org\":\"05807030-cfdb-4347-9110-d114c119418f\",\"addons-search-detection@mozilla.com\":\"f19765bc-576d-465f-9858-2d3a90b3d142\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"default-theme@mozilla.org\":\"01e135bc-518f-446b-873d-98c8e8fef69b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 1);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "d166d2ab-80a5-4287-855c-dfe86ff00773");
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2025-07-18T11:57:19.361Z\",\"featureIds\":[\"upgradeDialog\"],\"isRollout\":true,\"prefs\":[]}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"panelOpen\":false,\"launcherWidth\":0,\"launcherExpanded\":false,\"launcherVisible\":false,\"pinnedTabsHeight\":0,\"collapsedPinnedTabsHeight\":0}");
user_pref("sidebar.main.tools", "aichat,syncedtabs,history,bookmarks");
user_pref("sidebar.nimbus", "upgraded-sidebar-138-broad-rollout:rollout-treatment");
user_pref("sidebar.revamp", true);
user_pref("sidebar.revamp.defaultLauncherVisible", false);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.firefoxRelay.showToAllBrowsers", true);
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECGpaV2rbWeeOBAhR1UxpjSHm/Q==");
user_pref("toolkit.profiles.storeID", "b3e81456");
user_pref("toolkit.startup.last_success", 1752839838);
user_pref("toolkit.telemetry.cachedClientID", "5efe5a77-94e2-475d-a732-b51326624b97");
user_pref("toolkit.telemetry.cachedProfileGroupID", "94037ea1-d9e7-4170-93f0-5506e86f55bf");
user_pref("toolkit.telemetry.previousBuildID", "20250707120347");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
